[package]
name = "envsync-backend"
description = "EnvSync 后端抽象与实现"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
base64.workspace = true
envsync-crypto.workspace = true
envsync-domain.workspace = true
git2.workspace = true
thiserror.workspace = true
tracing.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile.workspace = true
